[package]
name = "enva-shared"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/photon-hq/enva"

[dependencies]
octocrab = "0.49.2"
url = "2.5.7"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
directories = "6.0.0"
